### ISSUE TITLE
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

### ISSUE THREAD

**Issue by gllmhyt** [numberly/mattermost-integration-giphy#11]
I'm unable to install this module, it seems to fail the installation of the `requests` package with the error `AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'`.
- Debian Jessie, up-to-date.
- Python 2.7.9

Bumping the version needed seems to make the installation working: it installs `requests==2.10.0` instead of 2.2.1.

**Comment by Lujeni** [comment]
Hello @postblue,

Thanks for your issue !
We will update the `setup.py`.

**Comment by gllmhyt** [comment]
Thank you very much!
