### ISSUE TITLE
Giphy logo points to 404 page

### ISSUE THREAD

**Issue by tealamore** [numberly/mattermost-integration-giphy#14]
This issue is the same as mattermost/mattermost-integration-giphy#13. A better link to use would be the avatar of giphy, which is https://avatars0.githubusercontent.com/u/3588525?v=3&s=200

**Comment by ultrabug** [comment]
I guess that's a fair point. @Lujeni @ramnes ?

**Comment by ramnes** [comment]
LGTM

**Comment by Lujeni** [comment]
https://github.com/numberly/mattermost-integration-giphy/commit/e495f942a77609c6381f743847fc8b7638c2733f

**Comment by ultrabug** [comment]
Thanks @Lujeni speed-of-light :)
