### ISSUE TITLE
Command with a trigger of 'gif' returned response 404 Not Found

### ISSUE THREAD

**Issue by tophat1720** [numberly/mattermost-integration-giphy#15]
i'm confused about what i should be exporting for the host and port numbers on my linux box..

**Comment by ramnes** [comment]
Can you give us more details like your configuration, what you're doing exactly, what's the expected result and what's the actual result?

**Comment by tophat1720** [comment]
I apologize. What I found was that when I specified the port in the callback URL (which wasn't asked for) I then received 405 error
