### ISSUE TITLE
 Command with a trigger of 'gif' returned response 301 Moved Permanently

### ISSUE THREAD

**Issue by tophat1720** [numberly/mattermost-integration-giphy#16]
Wasn't sure what to export my host to on my linux box.. so i tried my domain. my domain uses https but the server seems to run on http so i setup callback url at http://mydomain.com but doesn't seem to be doing the trick

**Comment by Lujeni** [comment]
Hi @tomtruitt,

Can you give us more details pls:
- environnement variables
- application log
- the mattermost callback

Thanks

**Comment by tophat1720** [comment]
I think this isn't an issue any more. But now I have 405.
