### ISSUE TITLE
Command with a trigger of 'giphy' returned response 404 Not Found

### ISSUE THREAD

**Issue by victorbello** [numberly/mattermost-integration-giphy#17]
I have tried all permutations of configuration available and cannot get this to work.

I've seen people say that adding the port to the callback url on the slash command helps, but if I do, all it does is timeout.

I've setup all the information on the bash_profile, key, port (5000), host (0.0.0.0), but nothing.

Any help would be greatly appreciated.

**Comment by Lujeni** [comment]
Hello @victorbello,

Did you have some logs?
Are you on heroku ?

Thansk

**Comment by victorbello** [comment]
I deployed on Heroku without issue, I have a problem now that the server dies every now and then, I need to figure out how to keep it up 100% of the time.

The one I had the issue with was deploying on a linux box, it wouldn't find the endpoint and kept getting 400 error, there was no log there, because the web server was never found.

**Comment by dabates** [comment]
I am also trying this.. followed the instructions several times.. this is on a linux install and not heroku.. 

My question is.. how does the system know what port to come back to, do we need to add that in the callback?

nothing in the error logs really

> 2016-09-01_15:20:49.19765 [2016/09/01 11:20:49 EDT] [EROR] /api/v3/teams/imfjoq71spfk5nty1hod7gb7ka/commands/execute:command code=500 rid=kccp1xqwdb85xcc7ympfmgna5o uid=jcx36purx3du5yzotw9pm77dgc ip=xxxx Command with a trigger of 'giphy' returned response 404 Not Found [details: ]

**update** 
Adding the port helped in the call back.. but now I'm getting a 405 method not allowed: POST
My call backurl is thus: http://myserver:5000

**Comment by Lujeni** [comment]
Same problem here https://github.com/numberly/mattermost-integration-giphy/issues/13.

I close this issue to keep a single thread.

Thanks
