### ISSUE TITLE
Mattermost v4

### ISSUE THREAD

**Issue by ghost** [numberly/mattermost-integration-giphy#25]
Anyone having an issue with giphy after upgrading to Mattermost 4.x ?

Giphys work in the public and private channels, but doesn't work for direct messages.

Gives the message "We couldn't find the existing team." in the UI, and logs the following in the console:

`2017/07/27 09:09:34 EDT] [EROR] /api/v4/commands/execute:SqlTeamStore.Get code=404 rid=xxxxxxx uid=xxxxxxxxx ip=0.0.0.0, 0.0.0.0 We couldn't find the existing team [details: id=]`

**Comment by pichouk** [comment]
This is a [known issue](https://mattermost.atlassian.net/browse/PLT-7193) with Slash commands on Mattermost `4.0`.
It will be fixed by [Mattermost `4.0.2`](https://forum.mattermost.org/t/mattermost-4-0-2/3576), which will be released in the next hours I guess.

**Comment by ghost** [comment]
Thanks for the quick update! Closing!

**Comment by pichouk** [comment]
FYI, the `4.0.2` update seems to be a little bit delayed, but should still fix this issue.
