### ISSUE TITLE
Command with a trigger of 'giphy' failed

### ISSUE THREAD

**Issue by krisgermann** [numberly/mattermost-integration-giphy#29]
When trying to test, I get the following error: Command with a trigger of 'giphy' failed

Error logs:

[2017/12/14 10:29:16 EST] [EROR] /api/v4/commands/execute:command code=500 rid=mhpqfqmih3fpdgqdz4o uid=hhpqaigchsom466gm6o ip=xxx.xxx.xxx.xxx Command with a trigger of 'giphy' failed [details: Post http://chat.domian.org:5000/new_post: dial tcp xxx.xxx.xxx.xxx:5000: i/o timeout]

I've run 'python run.py', and when I visit URL:5000 I get "OK" displayed.

Two questions:

1. What am I doing wrong here
2. How can I get run.py to run at startup, it's not working.

**Comment by Lujeni** [comment]
Hello @krisgermann 

Can you give us your mattermost version pls ?

**Comment by krisgermann** [comment]
Of course:

Mattermost Team Edition
Version: 4.4.0  (4.4.3)
Database: mysql

**Comment by krisgermann** [comment]
It may be important to note that I am using an Nginx reverse proxy for HTTP connections:

```
server {
   listen         80;
   server_name    domain;
   return         301 https://$server_name$request_uri;
}
 
server {
   listen 443 ssl;
   server_name domain;
 
   ssl on;
   ssl_certificate /etc/letsencrypt/live/domain/fullchain.pem;
   ssl_certificate_key /etc/letsencrypt/live/domain/privkey.pem;
   ssl_session_timeout 5m;
   ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
   ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
   ssl_prefer_server_ciphers on;
   ssl_session_cache shared:SSL:10m;
 
   location / {
      gzip off;
      proxy_set_header X-Forwarded-Ssl on;
      client_max_body_size 50M;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Frame-Options SAMEORIGIN;
      proxy_pass http://127.0.0.1:8065;
   }
}
```
 
Web access to the Mattermost server works, as do the mobile and desktop clients.

**Comment by Lujeni** [comment]
Do you have the log of the python application pls ?

**Comment by krisgermann** [comment]
Strangely enough, I updated some unrelated libraries on the Ubuntu VM it's running on, and it's now working... I'm unsure why.

**Comment by ramnes** [comment]
Glad you got it working. Feel free to re-open if needed.

**Comment by Hayyk** [comment]
@krisgermann can you mention what exactly you've updated?
