### ISSUE TITLE
Integration not working

### ISSUE THREAD

**Issue by jtommi** [numberly/mattermost-integration-giphy#33]
Hi,

I followed the Linux instructions, but when I try to use the slach command in the chat, I get "Command with a trigger of 'gif' failed".
When I check the mattermost logs, I see this : 
`{"level":"error","ts":1535273730.144273,"caller":"web/context.go:60","msg":"Command with a trigger of 'gif' failed","path":"/api/v4/commands/execute","request_id":"btuojx5tttnntyed7ifrwskdjc","ip_addr":"192.168.1.21","user_id":"s56ob3yxrpf1ucygnt6s6ckf3y","method":"POST","err_where":"command","http_code":500,"err_details":"Post http://192.168.1.4:8080/new_post: address forbidden"}`

192.168.1.21 is the client on which I use the webclient
192.168.1.4 is the server hosting everything.
I tried also with port 5000 and 8067 which I configured each time in the ~/.bash_profile and in the slach command configuration.

When I enter the URL http://192.168.1.4:8080/new_post manually in a browser, I see output in the integration server :
`[2018-08-26 10:52:38,697] [INFO] 192.168.1.21 - - [26/Aug/2018 10:52:38] "GET /new_post HTTP/1.1" 405 -`

I think I'm missing something, but I can't figure out what.

Any help would be appreciated.

The server is on Debian 9 and Python is 2.7.13

**Comment by NewEvolution** [comment]
The key is the `"err_details":"Post http://192.168.1.4:8080/new_post: address forbidden"`

By default, Mattermost blocks connections to internal IP blocks.  If you go to `System Console > Developer` you'll find the `Allow untrusted internal connections to:` field along with an explanation of its usage.

For your setup, whitelisting `192.168.1.4` should allow the integration to function.

**Comment by jtommi** [comment]
That worked perfectly, thanks a lot
