### ISSUE TITLE
Error during docker build

### ISSUE THREAD

**Issue by mechanicjay** [numberly/mattermost-integration-giphy#34]
```
unable to execute 'gcc': No such file or directory
==========================================================================
WARNING: The C extension could not be compiled, speedups are not enabled.
Failure information, if any, is above.
Retrying the build without the C extension now.

==========================================================================
WARNING: The C extension could not be compiled, speedups are not enabled.
Plain-Python installation succeeded.
==========================================================================

```

Adding the following to the Dockerfile fixed the error:
`RUN apk add build-base`

I can submit a pull request if you like.

**Comment by pichouk** [comment]
I don't know if it is something bad since you can still build the image. But LGTM to add it (merge it with the already existing `RUN` command)

**Comment by ramnes** [comment]
You shouldn't have to build the image yourself anymore since we now provide one!

https://hub.docker.com/r/numberly/mattermost-integration-giphy/
