### ISSUE TITLE
Add python-setuptools to install guide

### ISSUE THREAD

**Issue by simongavris** [numberly/mattermost-integration-giphy#36]
`sudo python setup.py install`
fails because setuptools is missing. (Ubuntu 18.04)
Consider adding `sudo apt-get install python-setuptools` to install-guide for a complete guide.

**Comment by monsieurp** [comment]
Hi dear maintainers! This is an easy one.

Please someone check out https://github.com/numberly/mattermost-integration-giphy/pull/37 and merge accordingly.

Thanks!

**Comment by ramnes** [comment]
Thank you @simongavris and @monsieurp :+1:
