### ISSUE TITLE
[ERROR] unable to handle new post :: tuple index out of range

### ISSUE THREAD

**Issue by h-town** [numberly/mattermost-integration-giphy#40]
This error shows up in both the app.py stdout as well as a post by the bot on mattermost: "tuple index out of range".  It seems more likely to be a python or dependency error so I apologize for seeking help here--I just can't figure out what's causing it.

**Comment by ramnes** [comment]
Did you close it because you found a solution? If so, what was the solution? Otherwise, could you share the whole traceback?

**Comment by h-town** [comment]
> Did you close it because you found a solution? If so, what was the solution? Otherwise, could you share the whole traceback?

hi @ramnes - i appreciate the follow-up, and my apologies for not having a chance to leave an explanation yesterday.  it turned out to be caused by a python error i made with some code revisions....now i hate it even more than i did before! :)

everything is working quite well.  thanks for your work!
