### ISSUE TITLE
Ubuntu 14.04 web server install

### ISSUE THREAD

**Issue by knoxor** [numberly/mattermost-integration-giphy#9]
Hi,

I've followed the instructions down as far as _Install integration requirements_ but am getting the following errors when running sudo python xxxx.py install:

python: can't open file 'setup.py': [Errno 2] No such file or directory

There is no setup.py file, there is a server.py file in the repo so I ran the command using this in case this was a typo but getting the following error:

Traceback (most recent call last):
  File "server.py", line 6, in <module>
    from flask import Flask

**Comment by bwets** [comment]
the git clone command in the instructions is actually incorrect, it should be https://github.com/numberly/mattermost-integration-giphy/

This solves the issue (the bad url is the one from the original implementation)

**Comment by bwets** [comment]
Also wrong in the instructions, is that the slash command should point to http://your server:5000/new_post

At least I had to do this to make it work

**Comment by knoxor** [comment]
thanks for that, I never noticed the incorrect url.

Seems to have an issue now with installing Flask

`Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [Errno 110] Connection timed out -- Some packages may not be found!
No local packages or download links found for Flask==0.10.1
error: Could not find suitable distribution for Requirement.parse('Flask==0.10.1')
`

I've downloaded the correct package using wget, do you know where I extract Flask locally so the script picks it up ?

thanks

**Comment by bwets** [comment]
Well, I dont know about that, I actually installed this on Ubuntu 16.04, so
that may have to do with the fact that giphy works.

On Tue, Apr 26, 2016 at 3:35 PM, knoxor notifications@github.com wrote:

> thanks for that, I never noticed the incorrect url.
> 
> Seems to have an issue now with installing Flask
> 
> Reading https://pypi.python.org/simple/
> Download error on https://pypi.python.org/simple/: [Errno 110] Connection
> timed out -- Some packages may not be found!
> No local packages or download links found for Flask==0.10.1
> error: Could not find suitable distribution for
> Requirement.parse('Flask==0.10.1')
> 
> I've downloaded the correct package using wget, do you know where I
> extract Flask locally so the script picks it up ?
> 
> thanks
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/numberly/mattermost-integration-giphy/issues/9#issuecomment-214746789

## 

Gregory Kieffer
30, Cite Im Thaelchen
L-6145 Junglinster
Luxembourg
00352 691 13 40 42

**Comment by knoxor** [comment]
I'll keep plugging away at this, installing on Ubuntu 14.04. Behind a proxy as well so maybe that has something to do with it.
Thanks for the help, much appreciated!

**Comment by ramnes** [comment]
Thanks for opening that issue, @knoxor.

As stated by @bwets (thanks for your attention!), the URLs in the README were wrong, and I fixed it.

I highly doubt that your issue with Flask installation is related to mattermost-integration-giphy, so I'm closing this issue. Don't hesitate to reopen if you think there's something we can do.
